const WRITING_NUMBER="WRITING_NUMBER";
const SELECT_OPERATOR="SELECT_OPERATOR";
const CALCULATE_RESULT ="CALCULATE_RESULT";
const RESET_OPERATION="RESET_OPERATION";
const ADD_DECIMAL_POINT="ADD_DECIMAL_POINT";
const DELETE_CHART="DELETE_CHART";
const PERCETAGE_TO_DECIMAL="PERCETAGE_TO_DECIMAL";
const ADD_PARENTHESES="ADD_PARENTHESES";


export {
    WRITING_NUMBER,
    SELECT_OPERATOR,
    CALCULATE_RESULT,
    RESET_OPERATION,
    ADD_DECIMAL_POINT,
    DELETE_CHART,
    PERCETAGE_TO_DECIMAL,
    ADD_PARENTHESES
}